spring:
  datasource:
    username: ${BOARD_MYSQL_USERNAME}
    password: ${BOARD_MYSQL_PASSWORD}
    url: jdbc:mysql://${BOARD_MYSQL_HOST}:${BOARD_MYSQL_PORT}/board
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace