spring:
  datasource:
    username: ${BOARD_MYSQL_USERNAME}
    password: ${BOARD_MYSQL_PASSWORD}
    url: jdbc:mysql://${BOARD_MYSQL_HOST}:${BOARD_MYSQL_PORT}/board
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${BOARD_REDIS_HOST}
      password: ${BOARD_REDIS_PASSWORD}
      port: ${BOARD_REDIS_PORT}
      database: ${BOARD_REDIS_DATABASE}
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace