version: "3.9"

services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace/:cached
    ports:
      - "8080:8080"
    networks:
      - default
  redis:
    image: redis:7.0.9-alpine
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env
    restart: on-failure
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    volumes:
      - ../redis:/data
    networks:
      - default
  mysql:
    image: mysql:8.0.35
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    restart: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ../mariadb:/var/lib/mysql --user 1000
    networks:
      - default

networks:
  default: